### ISSUE TITLE
Exceptions, try, catch, finally and Errors

### ISSUE THREAD

**Issue by vasanth0989** [vasanth0989/prep-myself#5]

**Comment by vasanth0989** [comment]
**Exceptions**

```yaml
Exceptions:
 description: 
 - Any abnormal in executing your program, example - NullPointerException
 - Exceptions can be recovered, you can recover from an exception using try, catch and finally block
 - IndexOutOfBound is an Exception
 types:
  - CheckedException | CompileTimeException:
    description:
     - Example are - IOException, say a method is throwing exception, the caller of the method needs to handle the exception.
     - Either they can rethrow it, they can hanlde it via try and catch block
     - If you are not doing either of this, meaning not handling using try/catch or not defined 'throws' in the method signature your code won't compile.
  - UnCheckedException | RunTimeException :
    - As the name denotes these type of exception only occur during Runtime
    - Examples are 'NullPointerException', 'IndexOutOfBoundException'
    - You don't need to handle this exception using 'try/catch' or declaring 'throws' inside method signature, your code will happily compile.
  
Errors:
 description:
  - You cannot recover, it's outside our control, example would be 'OutofMemoryError'

finally:
 description:
  - 'finally' block, will be added after 'try&catch' or it can be added just to the 'try' block
  - Just before your 'method return statement' the finally block gets executed.
  - Finally will always gets executed even if Exception occurs or not.
```
